In [108]:
# Importing modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from math import *

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import jaccard_similarity_score,accuracy_score,confusion_matrix,classification_report,log_loss,precision_score,recall_score

In [109]:
# Reading data
data=pd.read_csv('ChurnData.csv')
data.head(10)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0
5,68.0,52.0,17.0,120.0,1.0,24.0,0.0,1.0,0.0,20.70,...,0.0,0.0,0.0,0.0,0.0,3.030,3.240,4.787,1.0,0.0
6,42.0,40.0,7.0,37.0,2.0,8.0,1.0,1.0,1.0,8.25,...,0.0,1.0,1.0,1.0,1.0,2.110,3.157,3.611,4.0,0.0
7,9.0,21.0,1.0,17.0,2.0,2.0,0.0,0.0,0.0,2.90,...,0.0,0.0,0.0,0.0,0.0,1.065,3.240,2.833,1.0,0.0
8,35.0,50.0,26.0,140.0,2.0,21.0,0.0,1.0,0.0,6.50,...,0.0,0.0,1.0,1.0,0.0,1.872,3.314,4.942,3.0,0.0
9,49.0,51.0,27.0,63.0,4.0,19.0,0.0,1.0,0.0,12.85,...,0.0,1.0,1.0,0.0,1.0,2.553,3.248,4.143,2.0,0.0

In [110]:
# Converting churn column from float to int
data['churn']=data['churn'].astype('int')
data.head(5)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0

In [111]:
# SHAPE OF DIMENSION
data.shape

(200, 28)

In [112]:
# DATAFRAME TO ARRAY
x=np.asanyarray(data[['tenure','age','ed']])
y=np.asanyarray(data['churn'])

In [119]:
# train _test_ split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [120]:
# TRAIN THE MODEL
lr=linear_model.LogisticRegression()
lr.fit(x_train,y_train)
print(lr.score(x_test,y_test)*100)

80.0

In [121]:
# CROSS VALIDATION { 10-FOLD CV }
from sklearn.model_selection import cross_val_score
score=cross_val_score(lr,x,y,cv=10)

In [122]:
print('List of possible accuracy:',score)
print('Maximum accuracy that can be achived:',score.max())
print('Minimum accuracy that can be achived:',score.min())
print('Mean of the accuracy:',score.mean())
print('Standard deviation from mean accuracy:',score.std())

List of possible accuracy: [0.75 0.65 0.75 0.85 0.65 0.8  0.65 0.65 0.85 0.75]
Maximum accuracy that can be achived: 0.85
Minimum accuracy that can be achived: 0.65
Mean of the accuracy: 0.735
Standard deviation from mean accuracy: 0.0776208734813001

In [123]:
# STRATIFIES K-FOLD CROSS VALIDATION { 10-fold }
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=10,shuffle=True,random_state=3)
count=0
lst_accu_stratified=[]
for train_index,test_index in skf.split(x,y):
    count+=1
    print(count,"TRAIN:", train_index, "TEST:", test_index,'TRAIN_LEN',train_index.shape,'TEST_LEN',test_index.shape,sep='\n')
    x_train_fold,x_test_fold=x[train_index],x[test_index]
    y_train_fold,y_test_fold=y[train_index],y[test_index]
    lr.fit(x_train_fold,y_train_fold)
    lst_accu_stratified.append(lr.score(x_test_fold,y_test_fold))
print(lst_accu_stratified)

1
TRAIN:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  18
  19  20  21  22  23  25  27  28  29  30  31  33  34  35  36  37  38  39
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  81  82  83  84  85  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 103 104 105 106 107 108 109 110 111 113 114 116 117 118
 119 121 122 124 125 126 127 128 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 148 149 151 152 153 154 155 156 157 158 159
 160 161 163 164 165 166 167 168 169 170 171 172 174 175 176 177 179 180
 181 182 183 184 185 186 187 189 190 191 192 193 194 195 196 197 198 199]
TEST:
[ 17  24  26  32  40  57  80  86 102 112 115 120 123 129 147 150 162 173
 178 188]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
2
TRAIN:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  50  51  52  53  54  55  57  58
  59  60  61  62  64  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  93  94  95  97  99 100
 101 102 103 105 106 107 108 109 110 111 112 113 115 116 117 118 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 168 169 170 171 172 173 175 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 195 196 197 198 199]
TEST:
[ 21  22  23  49  56  63  65  91  92  96  98 104 114 119 140 141 167 174
 176 194]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
3
TRAIN:
[  0   2   3   4   5   6   8   9  10  11  12  13  14  15  16  17  20  21
  22  23  24  25  26  28  29  30  31  32  33  36  37  38  39  40  41  42
  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  61
  62  63  64  65  67  68  69  70  71  72  73  74  76  77  78  79  80  81
  82  83  85  86  87  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 132 134 135 137 138 139 140
 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158
 159 160 161 162 163 164 167 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 187 188 189 191 192 193 194 195 196 197 198 199]
TEST:
[  1   7  18  19  27  34  35  60  66  75  84  88 131 133 136 165 166 168
 186 190]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
4
TRAIN:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  31  32  34  35  37  39
  40  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  60  61  62  63  64  65  66  67  68  69  70  71  72  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 104 105 106 107 108 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 128 129 130 131 133 134 135 136
 138 139 140 141 142 144 145 146 147 148 149 150 152 153 155 156 157 158
 159 160 161 162 163 164 165 166 167 168 169 170 173 174 175 176 177 178
 179 180 181 183 184 185 186 187 188 190 192 193 194 195 196 197 198 199]
TEST:
[ 30  33  36  38  41  59  73 103 109 127 132 137 143 151 154 171 172 182
 189 191]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
5
TRAIN:
[  0   1   2   3   4   5   6   7   8  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  38  39  40  41  42  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  86  87  88  89  91  92  93  94  95  96  97  98
  99 100 101 102 103 104 105 106 107 108 109 111 112 113 114 115 116 117
 119 120 121 122 123 124 126 127 128 129 130 131 132 133 136 137 138 139
 140 141 142 143 145 146 147 148 150 151 152 153 154 155 157 158 159 160
 161 162 163 164 165 166 167 168 169 171 172 173 174 175 176 177 178 179
 180 181 182 183 185 186 188 189 190 191 192 193 194 195 196 197 198 199]
TEST:
[  9  37  43  44  45  46  67  85  90 110 118 125 134 135 144 149 156 170
 184 187]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
6
TRAIN:
[  0   1   3   4   5   6   7   8   9  10  11  12  13  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  55  56
  57  59  60  61  63  64  65  66  67  70  71  73  74  75  77  78  79  80
  82  84  85  86  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 108 109 110 111 112 113 114 115 117 118 119 120 122
 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140
 141 142 143 144 146 147 148 149 150 151 153 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
 179 180 181 182 184 185 186 187 188 189 190 191 192 194 196 197 198 199]
TEST:
[  2  14  54  58  62  68  69  72  76  81  83  87 107 116 121 145 152 183
 193 195]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
7
TRAIN:
[  0   1   2   4   6   7   8   9  10  11  12  13  14  15  17  18  19  20
  21  22  23  24  26  27  28  30  31  32  33  34  35  36  37  38  39  40
  41  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  62  63  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79
  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 102 103 104 105 106 107 108 109 110 112 113 114 115 116 118
 119 120 121 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 139 140 141 142 143 144 145 146 147 149 150 151 152 154 156 157 158 159
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
 180 181 182 183 184 186 187 188 189 190 191 193 194 195 196 197 198 199]
TEST:
[  3   5  16  25  29  42  61  64 101 111 117 122 138 148 153 155 160 179
 185 192]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
8
TRAIN:
[  1   2   3   5   6   7   8   9  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  29  30  31  32  33  34  35  36  37  38  40
  41  42  43  44  45  46  48  49  51  52  53  54  55  56  57  58  59  60
  61  62  63  64  65  66  67  68  69  70  72  73  74  75  76  77  78  79
  80  81  83  84  85  86  87  88  89  90  91  92  93  94  96  97  98  99
 101 102 103 104 107 108 109 110 111 112 113 114 115 116 117 118 119 120
 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 159 160 161 162 164 165 166 167 168 170 171 172 173 174 175 176 177 178
 179 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 197 199]
TEST:
[  0   4  10  28  39  47  50  71  82  95 100 105 106 142 158 163 169 180
 196 198]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
9
TRAIN:
[  0   1   2   3   4   5   6   7   8   9  10  12  14  15  16  17  18  19
  21  22  23  24  25  26  27  28  29  30  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50  54  56  57  58  59  60  61
  62  63  64  65  66  67  68  69  71  72  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  91  92  94  95  96  97  98  99
 100 101 102 103 104 105 106 107 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 129 130 131 132 133 134 135 136 137
 138 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156
 158 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 176 178
 179 180 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 198]
TEST:
[ 11  13  20  31  51  52  53  55  70  93 108 128 139 157 159 175 177 181
 197 199]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
10
TRAIN:
[  0   1   2   3   4   5   7   9  10  11  13  14  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  75  76  80
  81  82  83  84  85  86  87  88  90  91  92  93  95  96  98 100 101 102
 103 104 105 106 107 108 109 110 111 112 114 115 116 117 118 119 120 121
 122 123 125 127 128 129 131 132 133 134 135 136 137 138 139 140 141 142
 143 144 145 147 148 149 150 151 152 153 154 155 156 157 158 159 160 162
 163 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199]
TEST:
[  6   8  12  15  48  74  77  78  79  89  94  97  99 113 124 126 130 146
 161 164]
TRAIN_LEN
(180,)
TEST_LEN
(20,)
[0.85, 0.6, 0.7, 0.7, 0.75, 0.85, 0.65, 0.75, 0.75, 0.75]

In [124]:
from statistics import mean
from statistics import stdev
print('List of possible accuracy:',lst_accu_stratified)
print('Maximum accuracy that can be achived:',max(lst_accu_stratified))
print('Minimum accuracy that can be achived:',min(lst_accu_stratified))
print('Mean of the accuracy:',mean(lst_accu_stratified))
print('Standard deviation from mean accuracy:',stdev(lst_accu_stratified))

List of possible accuracy: [0.85, 0.6, 0.7, 0.7, 0.75, 0.85, 0.65, 0.75, 0.75, 0.75]
Maximum accuracy that can be achived: 0.85
Minimum accuracy that can be achived: 0.6
Mean of the accuracy: 0.735
Standard deviation from mean accuracy: 0.07835106182362105